# Conditions

```{r, include = FALSE}
source("common.R")
```

## Introduction

The job of the __condition__ system is to alert the user to problems and give them tools to handle them. In R, conditions encompass errors (`stop()`), warnings (`warning()`), and messages (`message()`), and other custom classes. It's important to understand the condition system because in your own code you'll need to both __signal__ conditions to the user, and to __handle__ conditions thrown by other functions.

R offers an exceptionally powerful condition handling system based on ideas from Common Lisp, but it's currently not very well documented or often used. This chapter will introduce you to the most important basics, but if you want to learn more, I recommend the following two sources:

* [_A prototype of a condition system for R_][prototype] by Robert Gentleman 
  and Luke Tierney. This describes an early version of R's condition system. 
  While the implementation has changed somewhat since this document was 
  written, it provides a good overview of how the pieces fit together, and 
  some motivation for its design.

* [_Beyond exception handling: conditions and restarts_][beyond-handling]
  by Peter Seibel. This describes exception handling in Lisp, which happens 
  to be very similar to R's approach. It provides useful motivation and 
  more sophisticated examples. I have provided an R translation of the 
  chapter at <http://adv-r.had.co.nz/beyond-exception-handling.html>.

### Overview {-}

* Discuss the details of signalling conditions
* Show the basic tools for ignoring conditions
* Dive into condition handlers, including the details of condition objects.
* Show a bunch of smaller applications.

### Quiz {-}

Want to skip this chapter? Go for it, if you can answer the questions below. Find the answers at the end of the chapter in [answers](#conditions-answers).

1. What are the four most important types of condition?

1. What function do you use to ignore errors in block of code?

1. Why might you want to create an error with a custom S3 class?

### Prerequisites

```{r setup}
library(rlang)

cnd_signal <- function(cnd) {
  switch(cnd_type(cnd), 
    error = cnd_abort(cnd),
    warning = cnd_warn(cnd),
    message = cnd_inform(cnd),
    condition = rlang::cnd_signal(cnd, .mufflable = TRUE)
  )
}

cnd_muffle <- function(cnd) {
  switch(cnd_type(cnd),
    error = abort("Can not muffle an error"),
    warning = invokeRestart("muffleWarning"),
    message = invokeRestart("muffleMessage"),
    condition = invokeRestart("muffle")
  )
}

# Waiting for lobstr update
cst <- function() print(rlang::calltrace(globalenv()))
```

## Signalling conditions
\index{errors!throwing}
\index{conditions!signalling}

There are three conditions that you can signal in code: errors, warnings, and messages. Errors are the most severe; they indicate that there is no way for a function to continue and force execution to terminate. Messages are the mildest; they are way of informing the user that some action has been performed. Warnings fall somewhat in between, and typically indicate that something has gone wrong but the function has been able to recover in some way. There is a final condition that can only be generated interactively: an interrupt, which indicates that the user has "interrupted" execution by pressing Escape, Ctrl + Break, or Ctrl + C (depending on the platform).

Conditions are usually displayed prominently, in a bold font or coloured red, depending on the R interface. You can tell them apart because errors always start with "Error", warnings with "Warning message", and messages with nothing.

```{r, error = TRUE}
stop("This is what an error looks like")

warning("This is what a warning looks like")

message("This is what a message looks like")
```

### Errors

In base R, errors are signalled, or __thrown__, by `stop()`:

```{r, error = TRUE}
f <- function() g()
g <- function() h()
h <- function() stop("This is an error!")

f()
```

By default, the error message includes the call, but this is typically not useful (and recapitulates information that you can easily get from `traceback()`), so I think it's good practice to use `call. = FALSE`:

```{r, error = TRUE}
h <- function() stop("This is an error!", call. = FALSE)
f()
```

The rlang equivalent, `rlang::abort()`, does not capture the call by default:

```{r, error = TRUE}
h <- function() abort("This is an error!")
f()
```

(Note that will `stop()` will paste together multiple inputs, `abort()` will not. To create complex error messages with abort, I recommend using `glue::glue()`. This allows us to use other arguments to `abort()` for useful features that faciliate custom condition objects.)

We'll use of `abort()` throughout this chapter, but we won't get to its most compelling feature, the ability to add additional metadata to the condition object, until we're near the end of the chapter.

The best error messages tell you what is wrong, and point you in the right direction for fixing the problem. Writing good error messages is extremely hard because usually the error occurs because the funtion caller has an incorrect mental model of the function. As a developer it's hard to predict how the mental model might be incorrect, especially when you've just written the function and the details are fresh in your mind. Often writing a good error message takes some iteration - you have to wait until someone sees it in the wild, and then you can talk to them to figure out what went wrong in their prediction of your function's behaviour. There is some evolving advice of writing good error messages in the tidyverse style guide: <http://style.tidyverse.org/error-messages.html>.

### Warnings

Warnings are weaker than errors: they signal that something has gone wrong, but the code has been able to recover and continue. They are generated by `warning()`. Unlike errors, you can have multiple warnings from a single function call:

```{r}
f <- function() {
  cat("1\n")
  warning("W1")
  cat("2\n")
  warning("W2")
  cat("3\n")
  warning("W3")
}
```

By default, warnings are cached and printed only when control returns to the top level:

```{r, eval = FALSE}
f()
#> 1
#> 2
#> 3
#> Warning messages:
#> 1: In f() : W1
#> 2: In f() : W2
#> 3: In f() : W3
```

You can control this behaviour with the `warn` option:

* To have warnings to appear immediately, set `options(warn = 1)`. 

* To turn warnings into errors, set `options(warn = 2)`. This is usually
  the easiest way to debug a warning, as once it's an error you can
  use tools like `traceback()` to find the source. 

* Restore the default behaviour with `option(warn = 0)`.

Like `stop()`, `warning()` also has a call argument. It is slightly more useful (since warnings are often more distant from their source), but I still generally suppress it with `call. = FALSE`. The rlang wrapper, `rlang::warn()`, also suppresses by default.

Warnings occupy a somewhat awkward limnal state between messages ("you should know about this") and errors ("you must fix this"). You should be cautious with your use of `warnings()`: warnings are easy to miss if there's a lot of other output, and you don't want your function to recover too easily from clearly incorrect input. In my opinion, base R tends to overuse warnings, and many warnings in base R would be better off as clear errors. For example, take `read.csv()`, which uses the the `file()` function. The file function simple warns if the file exists. That means that when you try and read a file that does not exist, you get both a warning and an error:

```{r, error = TRUE}
read.csv("blah.csv")
```

There are a few cases where warnings are clearly useful:

* When deprecating a function. A deprecated function still works, but you want
  to ensure users know that they need to transition to a new approach. A 
  deprecation warning should always help the user do the right thing.

* When you are reasonably certain you can recover from a problem.
  If you were 100% certain that you could fix the problem, you wouldn't need 
  any message; if you were uncertain that you could correctly fix the issue, 
  you'd throw an error.

### Messages

Messages are informational; use them to inform the user of important actions that you function has taken on their behalf. The key principle is don't try and be silently helpful. 

* Determining a function default that requires a lot of computation.
  For example, 
  
Generally any function that produces a message should have some way to suppress it, like `quiet = TRUE`. The user can always use `suppressMessages()`, but this the nuclear option as it suppresses all messages regardless of source.

Generally, you should use `message()` rather than `cat()` or `print()` for informing the user about actions that your function has taken. This is useful, for example, if you've had to do non-trivial computation to determine the default value of an argument, and you want to let the user know exactly what you've done. Messages are a side-channel. Functions that are primarily called for their printed output (like `print()` or `str()` methods), should use `cat()` to write directly to the console. 

Messages are also important when developing packages: when displaying messages during package startup (i.e. in `.onAttach()`), you must use `packageStartupMessage()`.

### Exercises

## Ignoring conditions 
\indexc{try()} \indexc{suppressWarnings()} \indexc{suppressMessages()}  

The simplest way of handling conditions in R is to simply ignore them. These are the bluntest instruments, but because they require little knowledge of the condition system, they're a good place to start.

`try()` allows execution to continue even after an error has occurred. Normally if you run a function that throws an error, it terminates immediately and doesn't return a value: 

```{r, error = TRUE}
f1 <- function(x) {
  log(x)
  10
}
f1("x")
```

However, if you wrap the statement that creates the error in `try()`, the error message will be printed but execution will continue:

```{r, eval = FALSE}
f2 <- function(x) {
  try(log(x))
  10
}
f2("a")
#> Error in log(x) : non-numeric argument to mathematical function
#> [1] 10
```

(You can suppress the message with `try(..., silent = TRUE)`.)

A useful `try()` pattern is to do assignment inside: this lets you define a default value to be used if the code does not succeed.

```{r, eval = FALSE}
default <- NULL
try(default <- read.csv("possibly-bad-input.csv"), silent = TRUE)
```

It is possible, but not recommended, to save the result of `try()` and perform different actions based on whether or not the result has class `try-error`. Instead, it is better to use `tryCatch()`, which we'll get to shortly.

There are two functions that are analagous to `try()` for warnings and messages: `suppressWarnings()` and `suppressMessages()`. These allow you to suppress all warnings and messages generated by a block of code.

```{r}
suppressWarnings({
  warning("Uhoh!")
})

suppressMessages({
  message("Hello there")
})
```

These functions are heavy handed: you can't use them to suppress a single warning that you know about, while allowing other warnings that you don't know about to pass through. We'll come back to that challenge later in the chapter.

### Exercises



## Handling conditions
\index{errors!catching}
\index{conditions!handling}

`tryCatch()` and `withCallingHandlers()` are general tools for handling conditions. They allows you to map conditions to __handlers__, functions that are called with the condition as an argument. `tryCatch()` and `withCallingHandlers()` differ in the type of handlers they create:

*  `tryCatch()` defines __exiting__ handlers; after the condition is captured 
   control returns to the context where `tryCatch()` was called. This makes 
   `tryCatch()` most suitable for working with errors and interrupts, as these 
   have to exit the code anyway.
  
*  `withCallingHandlers()` defines __calling__ handlers; after the condition
   is captued control returns to the context where the condition was signalled.
   This makes it most suitable for working with non-error conditions.

But before we can learn about these handlers, we need to talk a little bit about condition __objects__.  In simple usage, you never need to think about these objects, but they become explicit when you start working with the handlers.

### Condition objects
\index{conditions!objects}

So far we've just signalled conditions, and not looked at the objects created behind the scenes. Every time you signal a condition, R creates a condition object. The easiest way to get a condition object is to catch one from a signalled condition. That's the job of `rlang::catch_cnd()`:

```{r}
c <- catch_cnd(abort("An error"))
str(c)
```

A condition is a list with two elements: 

* `message`, a length-1 character vector containing the text display to a user.

* `call`, the call which triggered the conditin. As described above, we don't
  use this so it will always be `NULL`.

`conditionCall()`, `conditionMessage()`

Custom conditions can contain other components, which we'll discuss shortly in in [custom conditions].

Conditions also have a `class` attribute, which makes them S3 objects (the topic of [S3]). Fortunately, conditions are quite simple and you don't need to know anything about S3 to work with them. The most important thing to know now is that the elements of the class attribute determine what handlers will match the condition.

### Exiting handlers
\indexc{tryCatch()} \index{handlers!exiting}

Each condition has some default behaviour: errors stop execution and return to the top-level, warnings are captured, and messages are display. `tryCatch()` allows us to temporarily override the default behaviour and do something else. 

The basic form of `tryCatch()` is shown below. The named arguments set up handlers that will be called when the unnamed argument (`expr`) is evaluated. The handlers will usually be one of `error`, `warning`, `message`, or `interrupt` (the components of the condition class), and the function will be called with a single object, the condition.

```{r}
tryCatch(
  error = function(c) 10,
  stop("This is an error!")
)
```

If no conditions are signalled, or the signalled condition does not match the handler name, the code executes normally:

```{r}
tryCatch(
  error = function(c) 10,
  1 + 1
)

tryCatch(
  error = function(c) 10,
  {
    message("Hi!")
    1 + 1
  }
)
```

The handlers set up by `tryCatch()` are called __exiting__ handlers because after the condition is signal, control passes to the handler and never returns to the original code, effectively meaning that the code "exits":

```{r}
tryCatch(
  message = function(c) "There",
  {
    message("Here")
    stop("This code is never run!")
  }
)
```

Note that the code is evaluated in the environment of `tryCatch()`, but the handlers are not: they are functions. 

The argument to the handler is the condition object (hence, by convention, I use the name `c`). This is only moderately useful for the base conditions because they only have `message` and `call` fields. As we'll see shortly, it's more useful when you make your own custom conditions.

```{r}
tryCatch(
  error = function(c) c$message,
  stop("This is an error")
)
```

`tryCatch()` has one other argument: `finally`. It specifies a block of code (not a function) to run regardless of whether the initial expression succeeds or fails. This can be useful for clean up (e.g., deleting files, closing connections). This is functionally equivalent to using `on.exit()` (and indeed that's how it's implemented) but it can wrap smaller chunks of code than an entire function. \indexc{on.exit()}

### Calling handlers
\index{handlers!calling}

The handlers set up by `tryCatch()` are called exiting, because they cause code to exit once the condition has been caught. By contrast, the handlers set up by `withCallingHandler()` are __calling__: code execution will continue normally once the handler returns. This tends to make `withCallingHandlers()` a more natural pairing with the non-error conditions.

`tryCatch()` handles a signal like you handle a problem; you make the problem go away. `withCallingHandlers()` handles a signal like you handle a car, the car still exists.

```{r}
tryCatch(
  message = function(c) cat("Caught a message!\n"), 
  {
    message("Someone there?")
    message("Why, yes!")
  }
)

withCallingHandlers(
  message = function(c) cat("Caught a message!\n"), 
  {
    message("Someone there?")
    message("Why, yes!")
  }
)
```

Handlers are applied in order, so you don't need to worry getting caught in an infinite loop:

```{r}
withCallingHandlers(
  message = function(c) message("Second message"),
  message("First message")
)
```

If you have multiple handlers, and some handlers signal conditions, you'll need to think through the order carefully.

The return value of an calling handler is ignored because the code continues to execute after the handler completes; where would the return value go? That means that calling handlers are only useful for their side-effects. One important side-effect unique to calling handlers is the ability to __muffle__ the signal. By default, a condition will continue to propogate to parent handlers, all the way up to the default handler (or an exiting handler, if provided):

```{r}
# Bubbles all the way up to default handler which generates the message
withCallingHandlers(
  message = function(c) cat("Level 2\n"),
  withCallingHandlers(
    message = function(c) cat("Level 1\n"),
    message("Hello")
  )
)

# Bubbles up to tryCatch
tryCatch(
  message = function(c) cat("Level 2\n"),
  withCallingHandlers(
    message = function(c) cat("Level 1\n"),
    message("Hello")
  )
)
```

If you want to prevent the condition "bubbling up" but still run the rest of the code in the block, you need to explicitly muffle it with `rlang::cnd_muffle()`:

```{r}
# Muffles the default handler which prints the messages
withCallingHandlers(
  message = function(c) {
    cat("Level 2\n")
    cnd_muffle(c)
  },
  withCallingHandlers(
    message = function(c) cat("Level 1\n"),
    message("Hello")
  )
)

# Muffles level 2 handler and the default handler
withCallingHandlers(
  message = function(c) cat("Level 2\n"),
  withCallingHandlers(
    message = function(c) {
      cat("Level 1\n")
      cnd_muffle(c)
    },
    message("Hello")
  )
)
```

### Call stacks

To complete the section, there are some subtle differences between the call stacks of exiting and calling handlers. This generally is not important, unless you need to capture call stacks, but is included here becaus it's occassionally important to know about.
We can see this most easily by using `lobstr::cst()`

```{r}
f <- function() g()
g <- function() h()
h <- function() message("!")
```

* `withCallingHandlers()`: handlers are called in the context of the call that 
  signalled the condition
  
    ```{r}
    withCallingHandlers(f(), message = function(c) {
      cst()
      cnd_muffle(c)
    })
    ```

* `tryCatch()`: handlers are called in the context the call to `tryCatch()`. 

    ```{r}
    tryCatch(f(), message = function(c) cst())
    ```

### Exercises

1.  Predict the results of evaluating the following code

    ```{r, eval = FALSE}
    show_condition <- function(code) {
      tryCatch(
        error = function(c) "error",
        warning = function(c) "warning",
        message = function(c) "message",
        {
          code
          NULL
        }
      )
    }
    
    show_condition(stop("!"))
    show_condition(10)
    show_condition(warning("?!"))
    show_condition({
      10
      message("?")
      warning("?!")
    })
    ```

1.  Explain the results:

    ```{r}
    withCallingHandlers(
      message = function(c) message("a"),
      message = function(c) message("b"),
      message("c")
    )
    ```

1.  Read the source code for `catch_cnd()` and explain how it works.

1.  How could you rewrite `show_condition()` to use a single handler.

## Custom conditions
\index{conditions!custom}

One of the challenges of error handling in R is that most functions generate one of the default conditions, which consist only of a `message` and `call`. If you want to detect a specific error message, you must compute on the text of the error message. This is error prone, not only because the message might change over time, but also because messages can be translated into other languages. 

Fortunately R has a powerful but little used feature: the ability to use custom condition objects which can contain additional metadata. It is somewhat fiddly to create custom conditions in base R, but rlang makes it very easy: in `rlang::abort()` and friends you can supply a custom `.class` and additional metadata. 

```{r, error = TRUE}
abort(
  "Path `blah.csv` not found", 
  "error_not_found", 
  path = "blah.csv"
)

abort(
  "error_not_found",
  message = "Path `blah.csv` not found", 
  path = "blah.csv"
)
```

Custom conditions work just like regular conditions when used interactively. The big advantage comes when we program with them. The first place this is likely to happen is for you, if you are including this code in a package. Using custom conditions makes this testing errors much easier, and this alone, I think makes their usage worthwhile. (The same reasoning applies to messages and warnings too, but since they're lower stakes the cost-benefit ratio is a little different).

In the short-term, it is less likely that downstream users of your code will take advantage of the custom conditions. There's a bit of a chicken and egg situation when it comes to custom conditions: no one creates then so no one knows how to work with them, so no one creates them. Over time, however, as more people learn about and master the condition system, custom conditions will make it easier for the user to take different actions for different types of errors. For example, you could imagine the user of your function silently ignoring "expected" errors (like a model failing to converge for some input datasets), while unexpected errors (like no disk space available) can be propagated.

### Motivation

To explore these ideas in more depth, let's take `base::log()`. It does an ok job of providing errors about invalid arguments, but I think we can do even better:

```{r, error = TRUE}
log(letters)
log(1:10, base = letters)
```

I think we can do better by being explicit about which argument is the problem (i.e. `x` or base`), and being a little more helpful. I also don't think that repeating the function call is that useful.

```{r}
log <- function(x, base = exp(1)) {
  if (!is.numeric(x)) {
    abort("`x` must be a numeric vector; not ", typeof(x))
  }
  if (!is.numeric(base)) {
    abort("`base` must be a numeric vector; not ", typeof(base))
  }

  base::log(x, base = base)
}
```

This gives us:

```{r, error = TRUE}
log(letters)
log(1:10, base = letters)
```

This is a big improvement from the interactive point of view - the error messages are much more likely to yield a correct fix. However, from the programming point of a view, it's not a big win - all the data is jammed into a string. This makes it hard to program with, in particularly it makes it hard to test that we've done the right thing.

### Signalling

So let's build some infrastructure to improve this problem. We'll start by providing a custom `abort()` function for bad arguments. This is a little over-generalised for the example at hand, but it reflects common patterns that I've seen across other functions. The pattern is fairly simple. We create a nice error message for the user, using `glue::glue()`, and store metadata in the condition call for the developer. 

```{r}
abort_bad_argument <- function(arg, must, not = NULL) {
  msg <- glue::glue("`{arg}` must {must}")
  if (!is.null(not)) {
    msg <- glue::glue("{msg}; not {not}")
  }
  
  abort("bad_argument_error", 
    message = msg, 
    arg = arg, 
    must = must, 
    not = not
  )
}
```

We can now rewrite `my_log()` to use this new helper:

```{r}
log <- function(x, base = exp(1)) {
  if (!is.numeric(x)) {
    abort_bad_argument("x", must = "be numeric", not = typeof(x))
  }
  if (!is.numeric(base)) {
    abort_bad_argument("base", must = "be numeric", not = typeof(base))
  }

  base::log(x, base = base)
}
```

The code is not much shorter, but is a little more meanginful, and ensures that error messages for bad arguments is identical across functions. This yields the same interactive error messages as before:

```{r, error = TRUE}
log(letters)
log(1:10, base = letters)
```

### Handling

These structured condition objects make it much easier to test code. Rather than relying on regular expressions, you can now catch the condition object and inspect its elements.

```{r}
cnd <- catch_cnd(log("a"))
cnd$arg

cnd <- catch_cnd(log(1:10, base = "x"))
cnd$arg
```

Note that when using `tryCatch()` with multiple handlers and custom classes, the first handler to match any class in the signal's class hierarchy is called, not the best match. For this reason, you need to make sure to put the most specific handlers first:

```{r}
tryCatch(log("a"),
  error = function(c) "???",
  bad_argument_error = function(c) "bad_argument"
)

tryCatch(log("a"),
  bad_argument_error = function(c) "bad_argument",
  error = function(c) "???"
)
```

## Applications {#condition-applications}

What can you do with thse tools? The following section exposes some come use cases.

### Failure value

There are a few simple, but useful patterns based on returning a new value on failure. The simplest is to return a "default" value if there's an error.

```{r}
fail_with <- function(expr, value = NULL) {
  tryCatch(
    error = function(c) value,
    expr
  )
}
```

Another useful pattern is to work out if code can be evaluated successfully. This uses a slightly more complex pattern where we evaluate the user supplied code

```{r}
does_error <- function(expr) {
  tryCatch(
    error = function(c) TRUE,
    {
      expr
      FALSE
    }
  )
}
```

```{r}
safety <- function(expr) {
  tryCatch(
    error = function(c) {
      list(result = NULL, error = c)
    },
    list(result = expr, error = NULL)
  )
}
```

A slightly more sophisticated application is to construct a function that works like `try()`.
`base::try()` is more complicated in order to make the error message look more like what you'd see if `tryCatch()` wasn't used. 

```{r}
try2 <- function(expr, silent = FALSE) {
  tryCatch(expr, error = function(c) {
    msg <- conditionMessage(c)
    if (!silent) {
      message(msg)
    }
    structure(msg, class = "try-error")
  })
}

try2(1)
try2(stop("Hi"))
try2(stop("Hi"), silent = TRUE)
```

```{r}
catch_cnd <- function(expr) {
  tryCatch(
    condition = function(c) c, 
    {
      expr
      NULL
    }
  )
}
```


### Resignal

As well as returning default values when a condition is signalled, handlers can be used to make more informative error messages. For example, by modifying the message stored in the error condition object, the following function wraps `read.csv()` to add the file name to any errors:

```{r, error = TRUE, warning = FALSE}
read.csv2 <- function(file, ...) {
  tryCatch(read.csv(file, ...), error = function(c) {
    # message <- paste0(c$message, " (in ", file, ")")
    # abort(message)
  })
}
read.csv("code/dummy.csv")
read.csv2("code/dummy.csv")
```

Update to use whatever `rethrow()` becomes.

### Record

This is what the evaluate package does. It powers knitr. (A little more complicated because it also has to handle output which uses a different system.)

```{r}
catch_cnds <- function(expr) {
  conds <- list()
  add_cond <- function(c) {
    conds <<- append(conds, list(c))
    cnd_muffle(c)
  }
  
  withCallingHandlers(
    expr,
    message = add_cond,
    warning = add_cond
  )
  
  conds
}

catch_cnds({
  message("a")
  warning("b", call. = FALSE)
  message("c")
})
```

What if you also want to capture errors? You'll need to wrap the `withCallingHandlers()` in a `tryCatch()`. If an error occurs, it will be the last condition.

```{r}
catch_cnds <- function(expr) {
  conds <- list()
  add_cond <- function(c) {
    conds <<- append(conds, list(c))
    cnd_muffle(c)
  }
  
  tryCatch(
    error = function(c) {
      conds <<- append(conds, list(c))
      return()
    },
    withCallingHandlers(
      message = add_cond,
      warning = add_cond,
      expr
    )
  )
  
  conds
}

catch_cnds({
  inform("a")
  warn("b")
  abort("C")
})
```

### Return early

```{r}
try_parse_eval <- function(text, env = globalenv()) {
  expr <- tryCatch(parse(text = text), error = function(e) NULL)
  if (is.null(expr)) {
    return(NULL)
  }

  res <- tryCatch(eval(expr, env), error = function(e) NULL)
  if (is.null(res)) {
    return(NULL)
  }
  
  res
}

try_parse_eval <- function(text, env = globalenv()) {
  callCC(function(return) {
    expr <- tryCatch(parse(text = text), error = function(e) return(NULL))
    res <- tryCatch(eval(expr, env), error = function(e) return(NULL))
    res
  })
}

try_parse_eval("a + ")
try_parse_eval("a + b")
try_parse_eval("1 + 2")
```

### No default behaviour

```{r}
log <- function(message, level = c("message", "warning", "error")) {
  level <- match.arg(level)
  
  cnd <- cnd("log", level = level, .msg = message)
  cnd_signal(cnd)
}
```

:::base
If you create a condition object by hand, and signal it with `signalCondition()`; `cnd_muffle()` will not work. Instead you need to call it with a muffle restart defined, like this:

```R
withRestarts(signalCondition(cond), muffle = function() NULL)
```
:::


```{r}
record_log <- function(expr, path = stdout()) {
  withCallingHandlers(
    log = function(c) {
      cat(
        "[", c$level, "] ", c$message, "\n", sep = "",
        file = path, append = TRUE
      )
    },
    expr
  )
}

record_log(log("Hello"))

ignore_log_levels <- function(expr, levels) {
  withCallingHandlers(
    log = function(c) {
      if (c$level %in% levels) {
        cnd_muffle(c)
      }
    },
    expr
  )
}

record_log(ignore_log_levels(log("Hello"), "message"))
```

### Exercises

1.  Compare the following two implementations of `message2error()`. What is the
    main advantage of `withCallingHandlers()` in this scenario? (Hint: look
    carefully at the traceback.)

    ```{r}
    message2error <- function(code) {
      withCallingHandlers(code, message = function(e) stop(e))
    }
    message2error <- function(code) {
      tryCatch(code, message = function(e) stop(e))
    }
    ```

1.  Why is catching interrupts dangerous? Run this code to find out.

    ```{r, eval = FALSE}
    bottles_of_beer <- function(i = 99) {
      message("There are ", i, " bottles of beer on the wall, ", i, " bottles of beer.")
      while(i > 0) {
        tryCatch(
          Sys.sleep(1),
          interrupt = function(err) {
            i <<- i - 1
            if (i > 0) {
              message(
                "Take one down, pass it around, ", i, 
                " bottle", if (i > 1) "s", " of beer on the wall."
              )
            }
          }
        )
      }
      message("No more bottles of beer on the wall, no more bottles of beer.")
    }
    ```



## Quiz answers {#conditions-answers}

1. You could use `try()` or `tryCatch()`.

1. Because you can then capture specific types of error with `tryCatch()`,
   rather than relying on the comparison of error strings, which is risky,
   especially when messages are translated.

[prototype]: http://homepage.stat.uiowa.edu/~luke/R/exceptions/simpcond.html
[beyond-handling]: http://www.gigamonkeys.com/book/beyond-exception-handling-conditions-and-restarts.html
